
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}

  app:
    build:
      context: .
    restart: always
    container_name: produto-api        
    ports:
      - "3000:3000"      
    depends_on:
      - db        