
services:
  app:
      build:
        context: .
      restart: always
      container_name: produto-api        
      ports:
        - "3000:3000"      
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app-network
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: 'produto-api'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network: