services:
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}

  app:
    build:
      context: .
    restart: always
    container_name: produto-api
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db: